apiVersion: v1
kind: Service
metadata:
  name: nginx-headless
  labels:
    app: stateful-web
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: stateful-web
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-sts
spec:
  serviceName: "nginx-headless"
  replicas: 2
  selector:
    matchLabels:
      app: stateful-web
  template:
    metadata:
      labels:
        app: stateful-web
    spec:
      containers:
      - name: nginx
        image: nginx:1.25-alpine
        ports:
        - containerPort: 80
          name: web
